---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rishika-07
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: read-only-group
# spec:
#   type: team
#   children: []

# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: workflow-trigger-group
# spec:
#   type: team
#   children: []

# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: plugin-runner-group
# spec:
#   type: team
#   children: []
